services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: fc_auth_db
      MYSQL_USER: auth
      MYSQL_PASSWORD: auth_password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mysql-data: