apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
#  type: NodePort
  ports:
    - port: 3306
#      nodePort: 31000
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_0900_ai_ci
            - --default-time-zone=+09:00
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: TZ
              value: Asia/Seoul
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: initdb
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: fc_auth_db
  MYSQL_DATABASE_URL: "jdbc:mysql://mysql:3306/fc_auth_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
  initdb.sql: |
    SET NAMES utf8mb4;
    USE fc_auth_db;
    CREATE TABLE employee (id BIGINT AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(20), last_name VARCHAR(20), department_id BIGINT);
    INSERT INTO employee (first_name, last_name, department_id) VALUES ('길동', '홍', 1), ('제니', '김', 2), ('nathan', 'kim', 1);
    CREATE TABLE department (id BIGINT AUTO_INCREMENT PRIMARY KEY, dept_name VARCHAR(50), team_lead_id BIGINT);
    INSERT INTO department (dept_name, team_lead_id) VALUES ('인사팀', 1), ('IT팀', 2);