apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== #root_password
  MYSQL_USER: YXV0aA== #auth
  MYSQL_PASSWORD: YXV0aF9wYXNzd29yZA== #auth_password
