spring:
  application:
    name: fc-auth

  profiles:
    default: local

  docker:
    compose:
      # Docker Compose는 local 프로필에서만 활성화한다.
      enabled: false

  datasource:
    hikari:
      pool-name: fc-auth-pool
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Seoul
          batch_size: 50
        order_inserts: true
        order_updates: true

server:
  shutdown: graceful

kakao:
  client_id: e836a4ffe16e0a7b277d9c1905f63bb7
  client_secret: BBiu9cUCMZ5ZcbAnWbLX6IcZCblKNozR
  redirect_uri: http://localhost:8080/kakao/callback

logging:
  level:
    root: info
